# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@4.7.0
jobs:
  example-mend-sast-job:
    docker:
      # prebuilt image with java
      - image: cimg/openjdk:16.0.2
    steps:
      # execute Mend scan, curling the latest CLI. Remeber to set environmental variables (SAST Organization, SAST CLI Token, and SAST Server)
      - run: 
          name: Download Mend SAST CLI
          command: <(curl -LJO https://downloads-sast.whitesourcesoftware.com/sast-cli/linux/wssastcli)
      - run: 
          name: Run Mend SAST
          command: |
            ./wssastcli --dir ./ --app=circleci --baseline=true
            SAST_ORGANIZATION: lukebroganOrg
            SASTCLI_TOKEN: 6750955702bc3d92f08766780165f2b5251fde62f5d9e200dab1b0f626c87376
            SAST_SERVER: https://sast-demo.whitesourcesoftware.com
workflows:
  example-workflow:
    jobs:
      - example-mend-sast-job